services:

  mongo-db:
    image: mongo:8.2.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data: